### ISSUE TITLE
Sonic - Error in Sonic (misc.js #1049) Pather.useTeleport is not a function 

### ISSUE THREAD

**Issue by DarkHorseDre** [blizzhackers/kolbot-sonic#5]
Hey all,
Finally merged sonic with kolbot and got it started - problem is, as soon as it leaves town it gets this error.

As the files from sonic were copied over a fresh kolton install, I'm not sure what the error is.

Any idea's?

**Comment by laztheripper** [comment]
Sonic is an as-is repo to be used as a resource alongside kolbot. Kolbot/BH members will not be updating or bug fixing for it. Any issues you will have to solve for yourself.

**Comment by DarkHorseDre** [comment]
@laztheripper Oh, ok - I assumed it was uploaded here like this for similar purposes to kolbot!

**Comment by laztheripper** [comment]
All good
